name: Run Clean Win Prob

on:
  workflow_dispatch:

jobs:
  clean_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openpyxl

      - name: Run cleaning script
        run: python scripts/clean_win_prob.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/win/step_1/
          git commit -m "Automated data clean: move to step_1" || echo "No changes to commit"
          git push
