name: 08 Juice

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-final-juice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run soccer personal juice script
        run: |
          python scripts/soc_juiced.py

      - name: Run ncaab personal juice script
        run: |
          python scripts/ncaab_juiced.py

      - name: Run soccer personal juice script
        run: |
          python scripts/nhl_juiced.py

      - name: Commit and push final files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/win/final/final_soc_*.csv
          git add docs/win/final/final_ncaab_*.csv
          git add docs/win/final/final_nhl_*.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Build final odds with personal juice"
            git push
          fi
