name: 01 Raw Clean

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run raw_clean
        run: |
          python scripts/raw_clean.py

      - name: Normalize team names
        run: |
          python scripts/name_normalization.py

      - name: Fix DK manual dates
        run: |
          python scripts/time_fix.py
      
      - name: Validate games master
        run: |
          python scripts/validate_games_master.py

      - name: Upload games master validation errors
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: games_master_validation_errors
          path: docs/win/errors/games_master_validation_errors.csv


      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add docs/win/dump/csvs/cleaned/*.csv
          git add docs/win/games_master/*.csv
          git add docs/win/manual/first/*.csv
          git add mappings/need_map/no_map.csv docs/win/errors/name_normalization.txt
          git add docs/win/errors
          git commit -m "Raw clean + name normalization + date fix" || exit 0
          git push
